### ISSUE TITLE
Unknown and uncatchable API timeout

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/api#48]
Although working on dev, when recently releasing to live there was a timeout situation, where all 3 pm2 workers were running, no memory or CPU maxed, and pm2 caught no issues and showed no problems, and did not restart anything, but yet the 3 workers all blocked and requests timed out without any error.

It was particularly on permissions requests that the timeouts occurred, but that could be coincidental. It seems also that the workers did intermittently recover, as some other requests were able to continue OK during the same period. The API itself was able to respond as well, although at some points became totally unavailable for brief periods.

The main impact of this was that JCT, which uses the permissions endpoint heavily, received blocking timeouts as well. However all our own find/availability/metadata/permissions requests could potentially have been affected. It affects JCT more because their requests went to the old API which forwards to the new one, but can only forward to the BG server due to SSL terminations not being forwardable to cloudflare, so their requests were unable to take advantage of the cloudflare workers performing the calculation independently of the BG server. JCT have now pushed a change to their code to use our new API URLs, and to check for timeout after 3 seconds on their requests.

This was after the following commit:
https://github.com/oaworks/paradigm/commit/31d5b3c38ea3785750c05ce09c281f7d5ab88b99

But most likely due to substantive changes in an earlier commit:
https://github.com/oaworks/paradigm/commit/8e0bb02ecfbaee61969e323f9de869d705299fc5

Having looked through, the likely files to potentially cause an error were:
server/src/puppet.coffee
worker/src/api.coffee
worker/src/data/index.coffee
worker/src/src/crossref.coffee
worker/src/src/epmc.coffee
worker/src/svc/oaworks/permissions.coffee

So some settings in puppet have been commented out for now.

Permissions has been checked through, and seems OK, and has been extensively used in Gates dev work. So too with crossref and epmc.

api.coffee and index.coffee are both capable of breaking anything, being the two main entry points to the API and the connection point from API to index. So these are still being reviewed.

The immediate fix for this issue was to start reverting to earlier commits. Also, to start manually triggering a pm2 reload whenever the API started blocking. After a day of evaluating the code, the commits have been rolled forward again.

Given that the true cause is still unknown, manual monitoring is being carried out. Also a reload script to reload every 5 minutes was set up, which seems to ensure that the API keeps working for now. I'll turn this up to 10 minutes, then 30 minutes, etc while looking for timeouts over the next few days. (There are also new alerts set up specifically for this.)

With the reload script in place the main problem is essentially "solved", in that there have been no more timeouts because of the regular restarts. But this issue needs to stay open and should take top priority until the source of the timeouts is found.

**Comment by markmacgillivray** [comment]
A recommendation from this issue would be to prioritise moving away from our old infrastructure, to simplify the chance of such problems and reduce the effect of these problems on external users.

**Comment by markmacgillivray** [comment]
Steve and Anusha at CL also have sysadmin access and instructions on how to manually restart if necessary, however that hasn't been a concern since the 5-minute-restart script was put in place, and that's now being tested at 10 minutes.

**Comment by markmacgillivray** [comment]
Additional console logging of fetch URLs has been enabled for the live API, viewable on pm2 logs paradigm, to keep an eye on what is being called for during a timeout, if one happens again.

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you give me an update here?

Also, Louise has asked for an idea of the total time this issue was causing user visible problems, and how many users it may have affected. I'm presuming the former you know, but anyway to give an idea for the later from your side easily? We can say how many support tickets it brought, which may be enough, but if you have another metric that would be great.

**Comment by JosephMcArthur** [comment]
Any word here Mark? At least on if this is resolved and a rough length?

**Comment by markmacgillivray** [comment]
For up to about four hours it could have affected any user. However during that four hours it was only failing a small percentage of the time, mostly only for permissions requests, and mostly only for JCT. Nobody else reported any problem. We don't keep track of users so we don't know much about them unless they contact us with a problem. During the hour or so I was actively watching it while the issue was occurring, it failed twice for about a minute each time.

This is resolved in a way that keeps the system running but without knowledge of the cause. Work to find the cause will be ongoing this week if there is time.

**Comment by markmacgillivray** [comment]
There was also a couple of minutes downtime on the background machine in the last hour. However that was due to a different issue as far as I can tell, and nobody has chased us about it. I don't have time left just now to investigate that further but it looks like a more straightforward hardware/resourcing issue which we can discuss later in the week. Any further alerts while I sleep will be picked up by someone else if the system fails to respond.

**Comment by markmacgillivray** [comment]
No longer high priority as there is a solution in place but keep open for future checks

**Comment by JosephMcArthur** [comment]
Current status:

* no issues currently on live, but the "state" has be replicated by chance on dev now
* still having workers being taken down on a schedule on live

Plan:
* update management script to not take down services doing long run jobs
* move script to dev too

Explanation:
* Suspect a rouge query got the system (as on dev) to this state but unclear what query
* The index is so big that it can sometimes not crash / recover, while the workers/app crash, and this causes the system to become non-responsive

**Comment by JosephMcArthur** [comment]
Current status. Waiting/monitoring to see if the new code catches the exception as expected.

**Comment by markmacgillivray** [comment]
Still waiting/monitoring, all going well so far.

**Comment by JosephMcArthur** [comment]
Still going well? What does closing this look like?

**Comment by markmacgillivray** [comment]
There hasn't been any more similar failures. This issue will close the next time there is one, or let's say by end of March if there haven't been any.

**Comment by markmacgillivray** [comment]
We had the failure again today, I took a note of the error condition, I can customise the restart script for that now. So I'll be able to finish this issue this week. Today the API recovered as expected with the changes we had already made, but the index continued to return some slow responses - that's the bit we've been waiting for to fail again. Now we will be able to restart that when we see the same slowdown occurring in future. It took about 8 weeks for it to occur again.

**Comment by JosephMcArthur** [comment]
Perfect, thanks Mark! Appreciate you keeping your eye on the ball here.

Joseph McArthur
Assistant Director: Right to Research Coalition <http://righttoresearch.org>
Director / Founder: Open Access Button <http://openaccessbutton.org>
Twitter: @Mcarthur_Joe <https://twitter.com/Mcarthur_Joe>
Skype: joseph_mcarthur



On Tue, Mar 22, 2022 at 10:10 PM, markmacgillivray ***@***.***

**Comment by JosephMcArthur** [comment]
Another example here.

* https://shareyourpaper.org/funders/gates?doi=10.1021/acs.oprd.1c00139
* [DTG paper_rev_JD2_TO2_unmarked.docx](https://github.com/oaworks/api/files/8364525/DTG.paper_rev_JD2_TO2_unmarked.docx)

**Comment by JosephMcArthur** [comment]
https://github.com/oaworks/api/issues/48#issuecomment-1080845057 should've been on https://github.com/oaworks/discussion/issues/1852
