### ISSUE TITLE
Merge "paradigm" with "API" (and simplify paradigm down to OA.Works API needs)

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/api#50]
Our old API is currently in a repo called API, and uses what was the Noddy framework, which was based on Meteor.

We've developed our new API for cloudflare workers, under the development name of "paradigm". We considered maintaining paradigm as a separate framework from the OA.Works API code, but that may not be so well suited to our goals. So there are a few options:

* keep the current new structure, which has "paradigm" as a wraparound pseudo-framework for OA.Works API code. However this may make it less clear where or what OA.Works API code is.

* keep paradigm separate from API as a framework, and move the OA.Works specific code out to the API repo once we are done with the old API code. This makes it clear what part of the code is explicit to the API, but means there are separate repos to maintain which are of no use if we have no other use case for a separate framework. So this should probably only be done if we really do intend to use it as a separate framework for multiple projects.

* turn the paradigm repo into the API repo once we are ready to totally replace the old API code with paradigm code. This makes it easy to understand what OA.Works backend code is - it's just all the code in the API repo, and that's all we use it for. Note a question for this though would be where to put code such as for bigdeal or rscvd? As long as it is OK for those to be "in" an OA.Works backend "API" repo, then I think this option is the simplest and perhaps most appropriate for OA.Works longer term.

**Comment by markmacgillivray** [comment]
@JosephMcArthur a decision on this will be required soon-ish, say end of December at the latest.

**Comment by JosephMcArthur** [comment]
The latter makes the most sense to me too at this stage. But, a few things I want to check.

> Note a question for this though would be where to put code such as for bigdeal or rscvd? 
I think it's okay to leave them there, that's how it is now, right?

Other than renaming the repo, would you make any code / structure changes after this decision?

**Comment by markmacgillivray** [comment]
I'd probably get rid of the svc/... delineation, since we're just bumping the oaworks routes up to the top level anyway.

**Comment by markmacgillivray** [comment]
Also I would remove any bits and pieces of code that may be in there that we don't actually need, to make it simpler to maintain in future. I don't think there's much of that, but could be some. And whatever we do here, I'll probably re-arrange some of the utility stuff to do with dates, passcodes etc into subunits, so the oaworks stuff takes more precedence at the top level.

**Comment by JosephMcArthur** [comment]
To what extent is the dream of paradigm kept alive in option three if folks forked the repo, deleted the OA.Works service, and started their thing in it's place?

**Comment by markmacgillivray** [comment]
They could, but I'm not sure there would be much point. Most of the advantage of our code is what it does for OA.Works. We haven't succeeded in focusing on making a standalone framework, and it doesn't coincide with any of our other priorities.

**Comment by JosephMcArthur** [comment]
Okay, let's go for option three then. Unless you would advise differently now (seems like maybe you've thought about it as we've gone back and forth).

**Comment by markmacgillivray** [comment]
Not working on this quite yet but assigning to myself to keep all critical things to do up front.

**Comment by markmacgillivray** [comment]
I've been doing this inbetween other things, waiting for things to run etc. So assigning it too, to keep track of where time is being spent and relate to pending code commits, and discuss at meetings.

**Comment by markmacgillivray** [comment]
A simplified structure has been made, unnecessary code has been removed. Work continues here.

**Comment by markmacgillivray** [comment]
Ready to merge, but not done yet, should be next week.

**Comment by markmacgillivray** [comment]
Note, check the paradigm client code for more simplification, possibly only needed for login, and even that could change if accounts become obsolete...

**Comment by JosephMcArthur** [comment]
Would be useful to know what it looks like to close this in your mind Mark and how much time you need to get there. I think it's also worth a discussion of what "closed" looks like here too (but, not necessarily this week).

**Comment by markmacgillivray** [comment]
I want to simplify the client js code a bit more, as mentioned above, can probably combine into just one file needed for login pages. Or, if you're thinking login won't be needed anywhere in future, depending what features we keep, then even the login code could be dropped. This will take me a couple of hours, or zero hours if you're already certain you don't want logins in future (which I assume is unlikely).

The only other part I'm still looking at is simplifying the server/worker distinction, which I've already simplified a bit, but could perhaps get down further. This will take two or three hours more. 

Once the two above are done, I'll merge the current paradigm repo into our API repo, that will take a few minutes, and then this issue is done.

**Comment by JosephMcArthur** [comment]
Go ahead with server/worker as you desire.

For login, I think what your describing makes sense regardless given the
time investment. We are highly likely to need login. But, I'd like to
consider if a SAAS solution makes sense (especially in light of having you
around less). I know we've discussed this before, but I think the context
was different then. Let's save this for a call - this is a thing generally
on my mind.
