### ISSUE TITLE
Enable automated index updates

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/api#56]

**Comment by markmacgillivray** [comment]
We have update functions for indexes we use to track remote sources, such as crossref and unpaywall. They can be run any time, but should also be set to run every day. We haven't completed that yet due to previous issues we had with the live system causing an unknown error. The dev system can run the updates for the ones where we share the same dev and live index. So we need to finish this by adding a schedule to dev that doesn't go to live, and runs the necessary updates every day.

**Comment by JosephMcArthur** [comment]
This will ship as soon as permissions & deposit do.

**Comment by markmacgillivray** [comment]
Previous comment remains true.

**Comment by markmacgillivray** [comment]
I've tested this on dev and live for permissions affiliations (because it is small and simple) and it works. Tomorrow I'll check that it runs as expected on its own then I'll turn on other permissions and then bigger ones like crossref, oadoi etc. I'll keep this issue open for this week, but there's nothing left to actually do unless unexpected problems occur.
