### ISSUE TITLE
Get rid of codeship if still attached anywhere

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/api#61]
Codeship are increasing pricing, I don't think we use it any more anyway but need to check. There are still settings for the old API and the oaworks/website.

**Comment by markmacgillivray** [comment]
Confirming the state of this:

codeship deploys the oaworks/website, the openaccessbutton.org website. It deploys dev and live, and builds them, and for live it triggers ghostinspector tests. However this is only running every four to six months. So, even if I do nothing about it we could just manually trigger this every few months when it comes up. 

The only other thing I could find was for openforwhom, and has not run for over two years. I don't see any codeship settings for API code. 

I'll still keep the issue open to set up a githook at some point at least for master oaworks/website so we can get the tests to auto-run. But until this issue closes, just let me know if you need a pull for that.

**Comment by JosephMcArthur** [comment]
> The only other thing I could find was for openforwhom, and has not run for over two years. I don't see any codeship settings for API code.

This can be deleted

> So, even if I do nothing about it we could just manually trigger this every few months when it comes up.

Good to know

> I'll still keep the issue open to set up a githook at some point at least for master oaworks/website so we can get the tests to auto-run

👍

**Comment by JosephMcArthur** [comment]
I've made a change to embed https://github.com/oaworks/embed/commit/25559dc2ed589599c08a83f24968a055457715e5 but I don't see it turning up on the site. How is it deployed?

**Comment by JosephMcArthur** [comment]
@markmacgillivray can you write up some instructions for steve to do this?

**Comment by markmacgillivray** [comment]
Added to https://github.com/oaworks/embed/blob/develop/README.md

**Comment by JosephMcArthur** [comment]
Any chance you could also do a push live? I think there are some changes
sitting on dev.

**Comment by JosephMcArthur** [comment]
oaworks/website

Joe McArthur
Director / Co-Founder: OA.Works <https://oa.works>
The Open Access Button is now OA.Works! Find out more about our rebrand
<https://blog.oa.works/open-access-button-is-now-oa-works/>.
